FROM mongo:3.4.5

# Run mongo in port 17017 in host
# cd into nosql folder
# To Build container: docker build --rm -t radiorecorder_mongo .
# To Run container:
# docker run -itd -v $PWD/data:/data/db -p 17017:27017 --network radiorecorder --ip 192.168.0.11 --name radiorecorder_mongo radiorecorder_mongo